name: Wheels

on:
  pull_request:
    paths:
      - '**'
  push:
    paths:
      - '**'

env:
  FORCE_COLOR: 3

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-minor: ['10' '11', '12']

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Python 3.${{ matrix.python-minor }}
      uses: actions/setup-python@v4
      with:
        python-version: 3.${{ matrix.python-minor }}

    - uses: pypa/cibuildwheel@v2.16
      env:
        CIBW_BUILD: 'cp3${{ matrix.python-minor }}-*'
        CIBW_ARCHS_MACOS: universal2
        CIBW_ARCHS_WINDOWS: auto ARM64

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        path: wheelhouse/*.whl
